"""
Output Formatter

Converts AuditResult into:
  1. Structured JSON (machine-readable, for storage / downstream systems)
  2. Markdown report (human-readable audit summary)
"""

import json
from datetime import date


SEVERITY_EMOJI = {
    "HIGH":   "🔴",
    "MEDIUM": "🟡",
    "LOW":    "🔵",
    "INFO":   "⚪",
}


def to_json(audit_result, indent: int = 2) -> str:
    """Serialize AuditResult to a formatted JSON string."""
    d = audit_result.to_dict()
    return json.dumps(d, indent=indent, default=str)


def to_markdown(audit_result) -> str:
    """
    Render AuditResult as a human-readable Markdown audit report.
    Suitable for sharing with stakeholders or saving as a .md file.
    """
    r = audit_result
    findings = r.findings

    high   = [f for f in findings if f.severity == "HIGH"]
    medium = [f for f in findings if f.severity == "MEDIUM"]
    low    = [f for f in findings if f.severity == "LOW"]
    info   = [f for f in findings if f.severity == "INFO"]

    risk_bar = _risk_bar(r.risk_score)

    lines = [
        f"# Forensic-AI Audit Report",
        f"",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Company** | {r.ticker} |",
        f"| **Fiscal Year** | {r.fiscal_year} |",
        f"| **Audit Date** | {r.audit_date} |",
        f"| **Model** | {r.model_used} |",
        f"| **Chunks Analyzed** | {r.total_chunks_analyzed} |",
        f"| **Sections Reviewed** | {r.sections_reviewed} |",
        f"",
        f"---",
        f"",
        f"## Risk Score: {r.risk_score}/100",
        f"",
        f"`{risk_bar}`",
        f"",
        f"| Severity | Count |",
        f"|---|---|",
        f"| 🔴 HIGH | {len(high)} |",
        f"| 🟡 MEDIUM | {len(medium)} |",
        f"| 🔵 LOW | {len(low)} |",
        f"| ⚪ INFO | {len(info)} |",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        r.summary,
        f"",
        f"---",
        f"",
        f"## Findings",
        f"",
    ]

    for i, f in enumerate(findings, 1):
        emoji = SEVERITY_EMOJI.get(f.severity, "⚪")
        lines += [
            f"### {emoji} [{f.severity}] {f.title}",
            f"",
            f"**Section:** {f.section}  ",
            f"**Focus Area:** {f.focus_area.replace('_', ' ').title()}",
            f"",
            f"**Finding:**  ",
            f.detail,
            f"",
        ]
        if f.flagged_text:
            lines += [
                f"**Flagged text:**",
                f"> {f.flagged_text}",
                f"",
            ]
        if f.recommendation:
            lines += [
                f"**Recommendation:**  ",
                f.recommendation,
                f"",
            ]
        lines.append("---")
        lines.append("")

    lines += [
        f"## Focus Areas Audited",
        f"",
    ]
    for key in r.focus_areas_run:
        lines.append(f"- {key.replace('_', ' ').title()}")

    lines += [
        f"",
        f"---",
        f"",
        f"*Generated by Forensic-AI · {r.audit_date} · Model: {r.model_used}*",
        f"",
        f"*This report is for research and educational purposes only. "
        f"Not investment or legal advice.*",
    ]

    return "\n".join(lines)


def _risk_bar(score: int, width: int = 40) -> str:
    """ASCII progress bar for risk score."""
    filled = int((score / 100) * width)
    bar = "█" * filled + "░" * (width - filled)
    label = "LOW" if score < 35 else "MEDIUM" if score < 65 else "HIGH"
    return f"{bar} {score}/100 ({label})"
